id = "rainbow"
name = "Rainbow"
schema_version = 1
version = "1.1.0"
authors = ["Athan Xiao <athanseal@gmail.com>"]
description = "Rainbow theme for Zed"
repository = "https://github.com/athxx/zed-theme-rainbow"
